import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../../styles/Home.module.css'
import Menu from '../../components/menu'
import TeamCard from '../../components/teamCard'
import useSWR  from 'swr';

const inter = Inter({ subsets: ['latin'] })

const fetcher = (...args: [any, any]) => fetch(...args).then((res) => res.json())

export default function Tournament({id} :any) {
  id = 1
  const { data, error } = useSWR(`/api/tournaments/${id}`, fetcher)

  if (error) return <div>Failed to load</div>
  if (!data) return <div>Loading...</div>

  return (
    <>
      <Head>
        <title>Tournament Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Menu/>
        <div className={styles.container}>
        {/* row */}
        <div className={`${styles.containerItem} ${styles.containerItem3}`}>
            <div className={styles.profileImage}>
                <Image src="/images/default_player.png" fill
                    alt=''/>
            </div>
            <div className={styles.profileSummary}>
              <h2>{data.name}</h2>
              <h3>12 Teams</h3>
              <h3>Created: 26/01/23</h3>
            </div>
        </div>
        <div className={`${styles.containerItem} ${styles.containerItem3}`}>
            <h2>Teams</h2>
            <div className={styles.cardRow}>
              <TeamCard/>
              <TeamCard/>
              <TeamCard/>
              <TeamCard/>
              <TeamCard/>
              <TeamCard/>
              <TeamCard/>
              <TeamCard/>
              <TeamCard/>
              <TeamCard/>
              <TeamCard/>
              <TeamCard/>
            </div>
        </div>
      </div>
      </main>
    </>
  )
}
