import Image from 'next/image'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Menu from '../components/menu'
import TournamentCard from '../components/tournamentCard'
import Head from 'next/head'
import PlayerCard from '../components/playerCard'

const tourCardList = [1, 2, 3]
const teamCardList = [1, 2, 3, 4, 5, 6]

export default function Home() {
		return (
			<>
				<Head>
					<title>Home Page</title>
					<meta name="description" content="Generated by create next app" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<main>
				<Menu/>
				<div className={styles.container}>
					<div className={`${styles.containerItem} ${styles.containerItem4}`}>
						<h2>Featured Tournaments</h2>
							<div className={styles.cardRow}>
							{
								tourCardList.map(() => <TournamentCard key={""}/>)
							}
							</div>
					</div>

					<div className={`${styles.containerItem} ${styles.containerItem3}`}>
						<h2>Recommended Players</h2>
							<div className={styles.cardRow}>
							{
								teamCardList.map(() => <PlayerCard key={""}/>)
							}
							</div>
					</div>
				</div>
				</main>
			</>
		)
	}