import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Menu from '../components/menu'
import Home from './home'
import SignInPage from './signInPage'
import React from 'react'
import UserForm from '../components/forms/user'
import { useSession, signIn, signOut } from "next-auth/react"

const inter = Inter({ subsets: ['latin'] })

export default function Index() {

  // const [password, setPassword] = React.useState("");
	// const [email, setEmail] = React.useState("");
	// const [formSuc, setFormSuc] = React.useState(false);

	// const handleSubmit = (event: {
	// 	target: any; preventDefault: () => void;
	// }): void => {
	// 	event.preventDefault();
	// 	const data = { data: { email: email, password: password } };
	// 	const dataJSON = JSON.stringify(data);
	// 	// const data2 = JSON.parse(data)*/
	// 	fetch(event.target.action, {
	// 		headers: {
	// 			"Content-Type": "application/json",
	// 		},
	// 		body: dataJSON,
	// 		method: "POST",
	// 	}).then(() => { setFormSuc(true) });
	// };

	// const handleChange = (e: { target: { name: any; value: any } }) => {
	// 	const inputName = e.target.name;
	// 	const inputVal = e.target.value;

	// 	if (inputName === "email") {
	// 		setEmail(inputVal);
	// 	} else if (inputName === "password") {
	// 		setPassword(inputVal);
	// 	}
	// };

  // return (
  //   <>
  //       { formSuc ?
  //             <Home/> :
  //             <>
  //             <Head>
  //               <title>Login Page</title>
  //               <meta name="description" content="Generated by create next app" />
  //               <meta name="viewport" content="width=device-width, initial-scale=1" />
  //               <link rel="icon" href="/favicon.ico" />
  //             </Head>
  //             <main className={styles.main}>
  //               <div className={styles.grid}>
  //                 <UserForm/>
  //               </div>
  //             </main>
  //           </>
  //       }
  //   </>
  // )

  const { data: session, status } = useSession()
  const userEmail = session?.user?.email

  if (status === "loading") {
    return <p>Hang on there...</p>
  }

  if (status === "authenticated") {
    return (
        <Home/>
    )
  } else {
    return (
      <SignInPage/>
    )
  }
}
