import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Menu from '../components/menu'
import Home from './home'
import React from 'react'

const inter = Inter({ subsets: ['latin'] })

export default function Index() {

  const [password, setPassword] = React.useState("");
	const [email, setEmail] = React.useState("");
	const [formSuc, setFormSuc] = React.useState(false);

	const handleSubmit = (event: {
		target: any; preventDefault: () => void;
	}): void => {
		event.preventDefault();
		const data = { data: { email: email, password: password } };
		const dataJSON = JSON.stringify(data);
		// const data2 = JSON.parse(data)*/
		fetch(event.target.action, {
			headers: {
				"Content-Type": "application/json",
			},
			body: dataJSON,
			method: "POST",
		}).then(() => { setFormSuc(true) });
	};

	const handleChange = (e: { target: { name: any; value: any } }) => {
		const inputName = e.target.name;
		const inputVal = e.target.value;

		if (inputName === "email") {
			setEmail(inputVal);
		} else if (inputName === "password") {
			setPassword(inputVal);
		}
	};

  return (
    <>
        { formSuc ?
              <Home/> :
              <>
              <Head>
                <title>Login Page</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
              </Head>
              <main className={styles.main}>
                <div className={styles.grid}>
                  <a className={styles.card}>
                    <h3>Enter details &rarr;</h3>
                    {formSuc ? (
                      <h1>Success</h1>
                    ) : (
                      <form
                        action={`api/users/${email}`}
                        method="POST"
                        onSubmit={handleSubmit}
                      >
                        <label htmlFor="email">Email:</label>
                        <input
                          type="text"
                          id="email"
                          name="email"
                          value={email}
                          onChange={handleChange}
                          required
                        />
                        <br />

                        <label htmlFor="password">PW:</label>
                        <input
                          type="text"
                          id="password"
                          name="password"
                          value={password}
                          onChange={handleChange}
                          required
                        />
                        <br />
                        <br />

                        <button type="submit">Submit</button>
                        <br />
                      </form>
                    )}
                  </a>
                </div>
              </main>
            </>
        }
    </>
  )
}
