import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Menu from '../components/menu'
import TournamentCard from '../components/tournamentCard'

const inter = Inter({ subsets: ['latin'] })

export default function Tournaments() {
  return (
    <>
      <Head>
        <title>Tournaments Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Menu/>
        <div className={styles.container}>
        {/* row */}
        <div className={`${styles.containerItem} ${styles.containerItem3}`}>
            <h2>Tournaments</h2>
            <div className={styles.cardRow}>
              <TournamentCard/>
              <TournamentCard/>
              <TournamentCard/>
              <TournamentCard/>
              <TournamentCard/>
              <TournamentCard/>
              <TournamentCard/>
            </div>
        </div>
      </div>
      </main>
    </>
  )
}
