import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../../styles/Home.module.css'
import Menu from '../../components/menu'
import useSWR  from 'swr';
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import { useSession } from 'next-auth/react'
import TeamList from '../../components/teamList'

const inter = Inter({ subsets: ['latin'] })

const fetcher = (...args: [any, any]) => fetch(...args).then((res) => res.json())

export default function Profile() {
  const router = useRouter()
  const { data: session, status } = useSession()
  const id = router.query.id as string
  const [calledPush, setCalledPush] = useState(false)

  useEffect(()=>{
    if(status !== "loading"){
      if (status === "authenticated") {
        if(calledPush) return
        else {
          router.push(`/profiles/${id}`)
          setCalledPush(true)
        }
      }else{
        router.push('/')
        return setCalledPush(true)
      }
  }},[router,session])

  const { data: foundPlayer, error: playerError } = useSWR(calledPush ? `/api/players/${id}/teams` : null, fetcher);
  if(!foundPlayer) return <div>Loading...</div>
  if(playerError) return <div>Failed to load</div>

  if (typeof window !== "undefined" && status !== "authenticated") return null;

  if(foundPlayer) {
    console.log(foundPlayer)
  return (
      <>
        <Head>
          <title>Profile Page</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
        <Menu/>
          <div className={styles.container}>
          {/* row */}
          <div className={`${styles.containerItem} ${styles.containerItem1}`}>
              <div className={styles.profileImage}>
                  <Image src="/images/default_player.png" fill
                      alt=''/>
              </div>
              <div className={styles.profileSummary}>
                <h2>{foundPlayer.user.username}</h2>
                <h3>{foundPlayer.user.firstName} {foundPlayer.user.lastName}</h3>
                <h3>{foundPlayer.institute.name}</h3>
                <h3>Joined: {foundPlayer.user.createdAt}</h3>
                <h4>{foundPlayer != null ? "Verified":""}</h4>
              </div>
              <br/><br/>
          </div>
          <div className={`${styles.containerItem} ${styles.containerItem2}`}>
            <h2>Game Accounts</h2>
            <div className={styles.gameAccounts}>
                  <div className={styles.gameAccountItem}>
                    </div>
                  <div className={styles.gameAccountItem}>
                  </div>
                  <h2 className={styles.gameAccountItem}>Steam</h2>
                  <h2 className={styles.gameAccountItem}>Epic Games</h2>
            </div>
          </div>
          <div className={`${styles.containerItem} ${styles.containerItem3}`}>
              <h2>Teams</h2>
              <div className={styles.cardRow}>
                {
                  foundPlayer.teams.length > 0 ? <TeamList teams={foundPlayer.teams}/> : <h2>No Teams Found</h2>
                }
              </div>
          </div>
        </div>
        </main>
      </>
    )
  }
}

