import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '../../styles/Home.module.css'
import Menu from '../../components/menu'
import TournamentCard from '../../components/tournamentCard'
import PlayerCard from '../../components/playerCard'

const inter = Inter({ subsets: ['latin'] })

export default function Team() {
  return (
    <>
      <Head>
        <title>Team Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
      <Menu/>
        <div className={styles.container}>
        {/* row */}
        <div className={`${styles.containerItem} ${styles.containerItem3}`}>
            <div className={styles.profileImage}>
                <Image src="/images/default_player.png" fill
                    alt=''/>
            </div>
            <div className={styles.profileSummary}>
              <h2>Team1</h2>
              <h3>6 Members</h3>
              <h3>Created: 26/01/23</h3>
            </div>
        </div>
        <div className={`${styles.containerItem} ${styles.containerItem3}`}>
            <h2>Players</h2>
            <div className={styles.cardRow}>
              <PlayerCard/>
              <PlayerCard/>
              <PlayerCard/>
              <PlayerCard/>
              <PlayerCard/>
              <PlayerCard/>
              <PlayerCard/>
              <PlayerCard/>
              <PlayerCard/>
              <PlayerCard/>
              <PlayerCard/>
              <PlayerCard/>
            </div>
        </div>
      </div>
      </main>
    </>
  )
}
