import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../../styles/Home.module.css'
import Menu from '../../components/menu'
import TeamCard from '../../components/teamCard'
import useSWR  from 'swr';
import { useEffect } from 'react'
import { useRouter } from 'next/router'
import { useSession } from 'next-auth/react'

const inter = Inter({ subsets: ['latin'] })

const fetcher = (...args: [any, any]) => fetch(...args).then((res) => res.json())

export default function Tournament(props) {
  // id = 1
  const router = useRouter()
  const { data: session, status } = useSession()
  const id = router.query.id as string

  useEffect(()=>{
    if(status !== "loading"){
      if (status === "authenticated") {
        router.push(`/tournaments/${id}`)
      }else{
        router.push('/')
      }
  }},[router,session])

  if (status === "authenticated") {
    const { data, error } = useSWR(`/api/tournaments/${id}`, fetcher)

    if (error) return <div>Failed to load</div>
    if (!data) return <div>Loading...</div>
    return (

      <>
        <Head>
          <title>Tournament Page</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
        <Menu/>
          <div className={styles.container}>
          {/* row */}
          <div className={`${styles.containerItem} ${styles.containerItem3}`}>
              <div className={styles.profileImage}>
                  <Image src="/images/default_player.png" fill
                      alt=''/>
              </div>
              <div className={styles.profileSummary}>
                <h2>{data.name}</h2>
                <h3>{data.maxTeams} Teams</h3>
                <h3>Created: {data.createdAt}</h3>
              </div>
          </div>
          <div className={`${styles.containerItem} ${styles.containerItem3}`}>
              <h2>Teams</h2>
              <div className={styles.cardRow}>
                {/* <TeamCard/>
                <TeamCard/>
                <TeamCard/>
                <TeamCard/>
                <TeamCard/>
                <TeamCard/>
                <TeamCard/>
                <TeamCard/>
                <TeamCard/>
                <TeamCard/>
                <TeamCard/>
                <TeamCard/> */}
              </div>
          </div>
        </div>
        </main>
      </>
    )
  }
}
