import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '../../styles/Home.module.css'
import Menu from '../../components/menu'
import TeamList from '../../components/teamList'
import useSWR  from 'swr';
import { useEffect, useState } from 'react'
import { useRouter } from 'next/router'
import { useSession } from 'next-auth/react'
import JoinTeamForm from '../../components/forms/joinTeam'

const inter = Inter({ subsets: ['latin'] })

const fetcher = (...args: [any, any]) => fetch(...args).then((res) => res.json())

export default function Tournament(props) {
  const router = useRouter()
  const { data: session, status } = useSession()
  const id = router.query.id as string
  const [calledPush, setCalledPush] = useState(false)
  const [isDisplay, setDisplay] = useState(false)

  useEffect(()=>{
    if(status !== "loading"){
      if (status === "authenticated") {
        if(calledPush) return
        else {
          router.push(`/tournaments/${id}`)
          setCalledPush(true)
        }
      }else{
        router.push('/')
        return setCalledPush(true)
      }
  }},[router,session])

  const { data, error } = useSWR(`/api/tournaments/${id}`, fetcher)

  if (error) return <div>Failed to load</div>
  if (!data) return <div>Loading...</div>

  if (typeof window !== "undefined" && status !== "authenticated") return null;
  if(data) {
    console.log(data)
    return (
      <>
        <Head>
          <title>Tournament Page</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
        <Menu/>
          <div className={styles.container}>
          <button className={styles.joinButton} onClick={() => setDisplay(!isDisplay)}>Join tournament</button>
          {isDisplay ? <JoinTeamForm tournament={id} user={session.user.id}/> : null}
          {/* row */}
          <div className={`${styles.containerItem} ${styles.containerItem3}`}>
              <div className={styles.profileImage}>
                  <Image src="/images/default_player.png" fill
                      alt=''/>
              </div>
              <div className={styles.profileSummary}>
                <h2><b>{data.name}</b></h2>
                <h4>{data.maxTeams} Teams</h4>
                <h4>Created: {data.createdAt}</h4>
              </div>
          </div>
          <div className={`${styles.containerItem} ${styles.containerItem3}`}>
              <h2>Teams</h2>
              <div className={styles.cardRow}>
                {
                  data.partTeams.length > 0 ? <TeamList teams={data.partTeams}/> : <h4>No teams yet</h4>
                }
              </div>
          </div>
        </div>
        </main>
      </>
    )
  }
}
