import styles from '../styles/Home.module.css'
import Menu from '../components/menu'
import TournamentCard from '../components/tournamentCard'
import Head from 'next/head'
import PlayerCard from '../components/playerCard'
import TournamentList from '../components/tournamentList'
import useSWR from 'swr';
import { useSession, signIn, signOut } from "next-auth/react"
import SignInPage from './signInPage'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
import TeamList from '../components/teamList'

const teamCardList = [1, 2, 3, 4, 5, 6]

const fetcher = (...args: [any, any]) => fetch(...args).then((res) => res.json())

export default function Home(props) {

  const { data: session, status } = useSession()
	const { data, error } = useSWR('/api/home/recommend', fetcher);

	if (status === "loading") {
		return <p>Hang on there...</p>
	}

	if (error) return <div>Failed to load</div>
	if (!data) return <div>Loading...</div>
	if (typeof window !== "undefined" && status !== "authenticated") return null;

	if(data) {
		return (
			<>
				<Head>
					<title>Home Page</title>
					<meta name="description" content="Generated by create next app" />
					<meta name="viewport" content="width=device-width, initial-scale=1" />
					<link rel="icon" href="/favicon.ico" />
				</Head>
				<main>
				<Menu/>
				<div className={styles.container}>
					<div className={`${styles.containerItem} ${styles.containerItem3}`}>
						<h2>Featured Tournaments</h2>
							<div className={styles.cardRow}>
								{
									data.foundTours.length > 0 ? <TournamentList tournaments={data.foundTours} /> : <h3>No featured tournaments found</h3>
								}
							</div>
					</div>

					<div className={`${styles.containerItem} ${styles.containerItem3}`}>
						<h2>Recommended Players</h2>
							<div className={styles.cardRow}>
							{
								data.foundTeams.length > 0 ? <TeamList teams={data.foundTeams}/> : <h3>No recommended players found</h3>
							}
							</div>
					</div>
				</div>
				</main>
			</>
		)
	}

	return (
		<>
			<SignInPage/>
		</>
	)
}
