import Image from 'next/image'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Menu from '../components/menu'
import TournamentCard from '../components/tournamentCard'
import Head from 'next/head'
import PlayerCard from '../components/playerCard'
import TournamentList from '../components/tournamentList'
import useSWR from 'swr';
import { useSession, signIn, signOut } from "next-auth/react"
import SignInPage from './signInPage'

const teamCardList = [1, 2, 3, 4, 5, 6]

const fetcher = (...args: [any, any]) => fetch(...args).then((res) => res.json())

export default function Home(props) {
	
		const { data: session, status } = useSession()

		const { data, error } = useSWR('/api/home/recommend', fetcher);
		
		if (error) return <div>Failed to load</div>
		if (!data) return <div>Loading...</div>

		if (status === "loading") {
			return <p>Hang on there...</p>
		}
		
		if (status === "authenticated") {
			return (
				<>
					<Head>
						<title>Home Page</title>
						<meta name="description" content="Generated by create next app" />
						<meta name="viewport" content="width=device-width, initial-scale=1" />
						<link rel="icon" href="/favicon.ico" />
					</Head>
					<main>
					<Menu/>
					<div className={styles.container}>
						<div className={`${styles.containerItem} ${styles.containerItem4}`}>
							<h2>Featured Tournaments</h2>
								<div className={styles.cardRow}>
									<TournamentList tournaments={data.foundTours}/>
								{/* {
									tourCardList.map(() => <TournamentCard key={""}/>)
								} */}
								</div>
						</div>

						<div className={`${styles.containerItem} ${styles.containerItem3}`}>
							<h2>Recommended Players</h2>
								<div className={styles.cardRow}>
								{
									teamCardList.map(() => <PlayerCard key={""}/>)
								}
								</div>
						</div>
					</div>
					</main>
				</>
			)
		}

		return (
			<>
				<SignInPage/>
			</>
		)
	}