import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Menu from '../components/menu'
import Home from './home'
import React from 'react'
import UserForm from '../components/forms/user'
import { useSession, signIn, signOut } from "next-auth/react"
import useSWR	from 'swr';
import SignUpForm from '../components/forms/signUp'
import SignInForm from '../components/forms/signIn'

const inter = Inter({ subsets: ['latin'] })
export default function SignInPage(props) {

    return (
      <>
      <Head>
      <title>Login Page</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.credCenter}>
          <div className={styles.credCard}>
            <div>
              <h1>Sign in hi</h1>
              <SignInForm/>
              <br/>
              <h2>Or</h2>
              <br/>

              <h2>Sign In with Connected Accounts</h2>
              {/* Add connected account login */}
              {/* <button onClick={() => signIn("github")}>Sign in</button> */}

            </div>
            
            <div>
              <h1>Sign up</h1>
              <SignUpForm/>
            </div>
          </div>
        </div>
      </main>
      </>
    )
}
