import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import Menu from '../components/menu'
import TournamentList from '../components/tournamentList'
import useSWR	from 'swr';
import { useSession, signIn, signOut } from "next-auth/react"
import SignInPage from './signInPage'
import { redirect } from 'next/navigation';
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'
const inter = Inter({ subsets: ['latin'] })

const fetcher = (...args: [any, any]) => fetch(...args).then((res) => res.json())

export default function Tournaments(props) {

  const router = useRouter()
  const { data: session, status } = useSession()
  const [calledPush, setCalledPush] = useState(false)

  useEffect(()=>{
    if(status !== "loading"){
      if (status === "authenticated") {
        if(calledPush) return
        else{
          router.push('/tournaments')
          setCalledPush(true)
        }
      }else{
        router.push('/')
        setCalledPush(true)
      }
  }},[router,session])

    const { data, error } = useSWR('/api/home/recommend', fetcher);

    if (error) return <div>Failed to load</div>
    if (!data) return <div>Loading...</div>

    if (data) {
    return (
      <>
        <Head>
          <title>Tournaments Page</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
        <Menu/>
          <div className={styles.container}>
          {/* row */}
          <div className={`${styles.containerItem} ${styles.containerItem3}`}>
              <h2>Tournaments</h2>
              <div className={styles.cardRow}>
                {
                  data.foundTours > 0 ? <TournamentList tournaments={data.foundTours}/> : <h2>No Tournaments Found</h2>
                }
              </div>
          </div>
        </div>
        </main>
      </>
    )
  }

}
